config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'home/review'
  get 'home/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def review
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "David Obi", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "About", home_about_path, class:'nav-link' %>
      <%= link_to "Give Review", home_review_path, class:'nav-link' %>
      <a class="nav-link" href="https://realdavidobi.medium.com/" target="_blank" >Blog</a>
      <%= link_to "Contact", home_contact_path, class:'nav-link' %>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<br>
<p>
	Here I broke down my Journey/experience in a 3rd person narrative. Please feel free to visit any section that most interests you but do remember to read my pitch and you can get in touch.
</p>

<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          ChildHood
        </button>
      </h2>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        <p>
        	Born in Lagos Nigeria, David was a sports fan, playing in the streets with neighbours. When his dad travelled in 1999, he was sent to the middle belt (Benue State) to stay with his uncle and enroll in a boarding school. Sometimes, when he wasn't visited he went to the father of a friend he helps with mathematics and asked that he also be visited with provisions or he may not have the strength to help out his friend in maths.
        </p>
        <h5>Lessons Learnt</h5>
        <li>It is never too early or too late to think about turning passion into profit.</li>
        <li>Always strive to provide value.</li>
        	
        </p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          University
        </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
        
        <div class="card mb-3" style="max-width: 1040px;">
  			<div class="row no-gutters">
    			<div class="col-md-4">
     			 <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609776757/Personal%20Website/sirjoe_aw1hat.jpg" class="card-img" alt="..." height="400px" width="50%">
   				</div>
    			<div class="col-md-8">
      				<div class="card-body">
        				<h5 class="card-title">Studying Engineering</h5>
        				<p class="card-text">Fortunately, He got admission into University of Nigeria Nsukka to Study Electronic Engineering, One thing that kept him through is the end goal in mind, During his time, he co designed with Late Sir Joseph Ekene & Sir George Umeojiakor a Micro controller power source control system that is Mobile enabled. This sourse automatically searches all the phases of the house to select electricity that is within an acceptable voltage range or switches on the generator when it cannot find this voltage and then it can be turned off remotely via mobile phone.</p>
        				<h5>Lessons Learnt</h5>
        				<li>Surround yourself with people who lifts you up and brings out the best in you</li>
      				</div>
    			</div>
  			</div>
		</div>

      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          First Work Experience
        </button>
      </h2>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">
        
        <div class="card mb-3" style="max-width: 1040px;">
  			<div class="row no-gutters">
    			<div class="col-md-4">
     			 <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609776755/Personal%20Website/david_batterycharging_vjscpu.jpg" class="card-img" alt="..." height="200px" width="50%">
   				</div>
    			<div class="col-md-8">
      				<div class="card-body">
        				<h5 class="card-title">Life as an Avionics Engineer</h5>
        				<p class="card-text">His first Job was during his internship with the Nigerian Civia Aviation Authority, He fell in love with Aviation and ended up working with Onedot Aviation for his Service. At Onedot Aviation, He was tasked with the role of an Intern Avionics Engineer and Technical Records Officer. This task include; Charging of the Aircraft batters, Compass swing, Lighting, COmmunication Power check, as well as assisting the engineer on site. Due to his resourcefulness and love for ICT, he was also tasked with the development & management of the website of Onedot Aviation in 2016. Aviation was really fun and the experience truly is remarkable but still there wasnt that much fufulment for him because there was no free will to innovate in that line of operation. That was the start of his search into Entrepreneurship.</p>
        				<h5>Lessons Learnt</h5>
        				<li>In every position/job, the time you begin to grow is when you consider yourself a stakehoder in the job and strive to grow.</li>
        				<li>It doesn't matter if you are a novice, work until you it becomes difficult to let you go. If you are still scared of getting fired, you are not an asset.</li>
        				<li>If you are doing something that isnt giving you peace or fufilment, it is time to leave. Creativity is the opposite of competition.</li>
      				</div>
    			</div>
  			</div>
		</div>
      

      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingFour">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Entrepreneurship
        </button>
      </h2>
    </div>

    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
      <div class="card-body">
        David would always be grateful to Meltwater Entrepreneurial School of Technology. They train entreprepreneurs to build globally successful businesses by teaching, Software development, Communication, Business development & investing in businesses from idea stage. On completing the program in 2017, David Co founded his first company called Joluud, along with Luqman Musah and Joshua Oguntade. Joluud is a facilities management platform that helps facility managers plan, predict and execute maintenance operations and their costs.<br>
        Aside Joluud, David has also formed and failed in various businesses, an example is Cusites (Airline review/rating platform) & Oyaclean (connecting people to artisans on demand) which failed due to Covid. <br>
        Currently David started Truetesters (a platform to help businesses test against security vulnerabilities and mis configurations). He also helps businesses such as TracGlobal (vehicle tracking) in sales.
        <h5>Lessons Learnt</h5>
        <li>Entrepreneurship is hard, it is always advisable to have cash (capital) before you venture into it</li>
        <li>It is good to believe in what you do, but find other who you can convince and build with them, if you cannot convince one person, you cannot convince your customers.</li>

      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingFive">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          Sales & Marketing
        </button>
      </h2>
    </div>

    <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
      <div class="card-body">
        
        <div class="card mb-3" style="max-width: 1040px;">
  			<div class="row no-gutters">
    			<div class="col-md-4">
     			 <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609776756/Personal%20Website/davidjorn_hcdvdx.jpg" class="card-img" alt="..." height="260px" width="50%">
   				</div>
    			<div class="col-md-8">
      				<div class="card-body">
        				<h5 class="card-title">Sales Engineer</h5>
        				<p class="card-text">One thing he loves the most is Sales. Most times he tries to mathematically interpreat sales as it is always dependent on the number of people you reach out to. David specializes in door to door sales, sales prospecting, calls and email, pitching and customer retention. He has a process and uses hubspot to automate his leads managing process. On Sales, he headed Joluud sales process for 3 years and worked as a sales consultant for Traila Technologies from July until september 2020. David also has a process for leads qualifying and cold emailing where he uses automation tools like lemlist, anymailer, icyleads and targets decision makers with captivating messages.</p>

      				</div>
    			</div>
  			</div>
		</div>
      
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingSix">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseSix" aria-expanded="false" aria-controls="collapseOne">
          Ethical Hacking
        </button>
      </h2>
    </div>

    <div id="collapseSix" class="collapse" aria-labelledby="headingSix" data-parent="#accordionExample">
      <div class="card-body">
        Due to covid, a lot crashed for David and he was Jobless for a while, He started learning about ethical penetration testing and got attacted to this. He tests web, mobile, API's for vunerabilities and performs social engineering on target clients in order to prepare them against such attacks. He is very conversant with network based attacks involving active networks and offers mitigation against these attacks.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingSeven">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
          Webdesign & Development
        </button>
      </h2>
    </div>

    <div id="collapseSeven" class="collapse" aria-labelledby="headingSeven" data-parent="#accordionExample">
      <div class="card-body">
        In 2021, David was inspired by a his friend (Joseph) to learn rails. He started out with ruby and then rails, hes developed a few applications with rails, built this website in rails and continues to improve his knowledge in web development using rails. Further down the year (march), David would add React to compliment his knowledge in rails and enhance his websites further while maintaning ethical security principles. David loves to work with algorithms, and think through problems
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingEight">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseEight" aria-expanded="false" aria-controls="collapseOne">
          My Pitch
        </button>
      </h2>
    </div>

    <div id="collapseEight" class="collapse" aria-labelledby="headingEight" data-parent="#accordionExample">
      <div class="card-body">
        <div class="card mb-3" style="max-width: 1040px;">
  			<div class="row no-gutters">
    			<div class="col-md-4">
     			 <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609776755/Personal%20Website/david_yis615.jpg" class="card-img" alt="..." height="300px" width="50%">
   				</div>
    			<div class="col-md-8">
      				<div class="card-body">
        				<h5 class="card-title">Value I can add to your company</h5>
        				<p class="card-text">If you have a system in place and you are looking for a person full of energy, ready to collaborate and work with your team in pushing your company further. If you are looking for a friend that is ready to use his experience and versitility to push your company. If you can afford accomodation, feeding and a basic salary and have clearly defined tasks to be completed? I am your man. I love working with companies to figure out how to improve upon an existing process with data and result. I love working with people and having pure non judgemental fun & my smile is contagious. I am available for remote work also & can work part time. Please get in touch</p>
        				<p class="card-text"><small class="text-muted">Whatsapp: +233243611152, Email:  realdavidobi@gmail.com </small></p>
      				</div>
    			</div>
  			</div>
		</div>
      </div>
    </div>
  </div>
</div>

app/views/home/contact.html.erb
<p>Contact Page</p>

app/views/home/index.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609847583/Personal%20Website/mest2018_xcxlls.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Mest 2017 Guest lecture</h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609847758/Personal%20Website/46514106_2454058371290804_4536078432055853056_o_o4yddf.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Munich Members Meetup</h5>
        <p>During our visit to Germany, We stopped by to visit the Munich members and we indoctrinated into the club.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609847679/Personal%20Website/dusseldolf_o4qbod.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>German Consulate Berlin</h5>
        <p>Speaking with German consulate on the opportunities in Ghana and how we do not want aid but investment to grow and become creative.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br>

<br>

<div class="card mb-3" style="max-width: 740px;">
  <div class="row no-gutters">
    <div class="col-md-3">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609850199/Personal%20Website/7277c1c1-d584-4e1f-bc47-edf612cd4ac5_ajp8yj.jpg" class="card-img" alt="..." height="250px" width="30%">
    </div>
    <div class="col-md-9">
      <div class="card-body">
        <h5 class="card-title">You are welcome</h5>
        <p class="card-text">My name is David Obi, I am a definition of Resilence and consistency with experience in sales, web development, & ethical computer security. You are welcome to my page but first please have a look at friends who helped build me up.</p>
      </div>
    </div>
  </div>
</div><br>
<h3>I would forever remain grateful to the following friends</h3><br>

<div class="row row-cols-1 row-cols-md-3">
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849903/Personal%20Website/udensi_clement_menvht.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Clement Udensi</h5>
        <p class="card-text">Clement is my brother and teacher. I Learnt about consistency and focus from Clem and i see that in his daily life to this day. He is also a gifted React Developer.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849902/Personal%20Website/tony_marfo_apgkax.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Tony Marfo</h5>
        <p class="card-text">I used to say that tony is a symbol of what I wanna be when I grow up lol. A quality I still am learning from him is the act of patience in life, relationships and business. Without tony, I probably would be telling a totally different story on how i couldnt go further.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849901/Personal%20Website/luqman_nl1dpu.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Luqman Musah</h5>
        <p class="card-text">Luqman, is a friend, business partner and a brother all in one. We have survived the worst storms in our business without going astray simply because of his business ethics. I just want to always say thank you.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849901/Personal%20Website/joseph_kossi_namper.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Joseph Kossi</h5>
        <p class="card-text">What I admire most about Joe is his love for code and financial management abilities. I owe any amount I make from coding to Joe. He has been an inspiration, helper and his trive to constantly improve in code is my motivation to learn any language</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849901/Personal%20Website/kwame_owusu_l2u3z6.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Kwame Owusu</h5>
        <p class="card-text">Kwame is selfless, never seen him angry ever and always willing to help and offers really great ideas, I have never had a bad deal with Kwame & I sometimes think he makes losses just to maintain our transactions. My man anyday.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849903/Personal%20Website/charlette_ys7v2k.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Charlette N'guessan</h5>
        <p class="card-text">People say you either have beauty or brains, Well Charlette has got both, Words fail me when I try to describe accurately who she is. She's my adviser & my friend. This is definitely a brother zone I am happy to reside in cus shes got so much potential. Co-founding the only AI powered facial recognition platform in Ghana</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849902/Personal%20Website/pheobe_w28kpa.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Agbo Pheobe</h5>
        <p class="card-text">You do not need a reason to love Oge, she is smart, godly, pretty and thinking about her back in school was a source of sanity for me. I am truly looking forward to her invention & you should too.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849904/Personal%20Website/arinze_ugwu_k7ktcz.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Arinze Ugwu</h5>
        <p class="card-text">Everday I pray to God to make me as kind as Arinze. I mean things he does for people, way out of his way just to help. I love you man. God bless you.</p>
      </div>
    </div>
  </div>
  
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849902/Personal%20Website/mashosho_x0db7z.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Ogar Mathias</h5>
        <p class="card-text">I never really loved myself in secondary school and felt like I should not exist. Mathias changed my view in life and with unexplained reasons became my first true friend in life. Even in the military, I love his business acumen and look forward to doing things with my brother soon.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849901/Personal%20Website/ezenwa_martins_znujr2.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Martins Ezenwa</h5>
        <p class="card-text">Mr math martins as I always call him is a friend indeed, Martins is sharp, pratical and a go getter. I am humbled by his experience and always look up to him.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609849903/Personal%20Website/ocheja_patrick_lcjh3m.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Patrick Ocheja</h5>
        <p class="card-text">I cannot end this list without Patrick. I probably would not achieve anything I have after school without patrick. He is an inspiration and a strong partner to discuss and implement public and private startup ideas.</p>
      </div>
    </div>
  </div>
  <div class="col mb-4">
    <div class="card h-100">
      <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609854092/Personal%20Website/Screenshot_2021-01-05_at_13.41.01_smkh1p.png" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Kwabena </h5>
        <p class="card-text">Kwabee as I call him, is my mentor. Most times I find myself struggling with work, hes always there to direct me. Kwabee is a radiology expert and has built a solution for medical doctors to easy their operations. </p>
      </div>
    </div>
  </div>
</div>
<br>

<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Fun Activities</h5>
        <p class="card-text">I believe that we work to live life and not the other way around. I love exercise & perform professional massages & dance</p>
        <p>
  <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Exercise</a>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">Dance & massage</button>
  
</p>
<div class="row">
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample1">
      <div class="card card-body">
        This include weight lifting, swimming & meditation. I do this because I love to look fit, approachable and I need that rush of adrenaline when I wake up in the morning.
      </div>
    </div>
  </div>
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample2">
      <div class="card card-body">
        I enjoy anything that makes the body feel free, this include dancing, giving & receiving massages occassionally.
      </div>
    </div>
  </div>
</div>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Goal for 2021</h5>
        <p class="card-text">2020 has been a pretty tough ride, for 2021 my focus is purely on 3 things, Software development, Relationships and Sales.</p>
        <p>
  <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample3" role="button" aria-expanded="false" aria-controls="multiCollapseExample3">Software Development</a>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#multiCollapseExample4" aria-expanded="false" aria-controls="multiCollapseExample4">Relationships & Sales</button>
  
</p>
<div class="row">
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample3">
      <div class="card card-body">
        My goal this year is to be proficient in Rails and in march I would start React. Upon completion i should be able to handle projects in these areas pretty comfortably. I currently have two fully built projects on my Github but would push more as I continue in my Journey.
      </div>
    </div>
  </div>
  <div class="col">
    <div class="collapse multi-collapse" id="multiCollapseExample4">
      <div class="card card-body">
        I really hope to improve my relationships with people, get more involved and truly connect as a person and a friend. I have a problem with remembering names and I use a notepad but I would actively work on that and contually improve. This actually ties into sales, My approach however in sales is working on improving my conversion ratio, in Emails, Calls, pitching, Visits and even B2C sales.
      </div>
    </div>
  </div>
</div>
      </div>
    </div>
  </div>
</div> <br>
</div>


<div class="card">
  <div class="card-body">
    <h5 class="card-title">Meltwater Berlin Team</h5>
    <p class="card-text">My visit to the meltwater office in Berlin. Their passion is contagious and this continually reminds me on why relationships is vital</p>
  </div>
  <img src="https://res.cloudinary.com/dmgcn668q/image/upload/v1609847217/Personal%20Website/meltwatergermany_yvxld1.jpg" class="card-img-bottom" alt="...">
</div>

app/views/home/review.html.erb
<p>Reviews Page</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>David Obi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="container">
    <%= render 'home/header' %>
   <%= yield %>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

   
  </body>
</html>